name: scanner
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_riverpod: ^0.14.0+1
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  state_notifier: ^0.7.0
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.0.5
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter:

  uses-material-design: true
